# =============================================================================
# Powerlevel10k Configuration
# =============================================================================
# Generated by `p10k configure`. Run it again to customize.
# This is a lean configuration optimized for development workflows.
#
# To customize, run `p10k configure` or edit this file.
# =============================================================================

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Enable instant prompt mode (reduces shell startup time)
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # =============================================================================
  # Left Prompt Elements
  # =============================================================================
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # OS icon
    dir                     # Current directory
    vcs                     # Git status
  )

  # =============================================================================
  # Right Prompt Elements
  # =============================================================================
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # Exit code of the last command
    command_execution_time  # Duration of the last command
    background_jobs         # Background jobs indicator
    node_version            # Node.js version
    context                 # User@hostname (shown if root or remote)
    time                    # Current time
  )

  # =============================================================================
  # Basic Settings
  # =============================================================================

  # Use Unicode characters for prompt
  typeset -g POWERLEVEL9K_MODE='nerdfont-complete'

  # Prompt on a single line or multiple
  typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false

  # Add newline before each prompt
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Connect segments with arrow
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' '

  # =============================================================================
  # Directory Settings
  # =============================================================================

  # Truncate directory path
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_last'

  # Directory colors
  typeset -g POWERLEVEL9K_DIR_BACKGROUND='blue'
  typeset -g POWERLEVEL9K_DIR_FOREGROUND='white'
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='white'
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='white'
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

  # =============================================================================
  # Git/VCS Settings
  # =============================================================================

  # Show these git status indicators
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '

  # Git colors
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='red'
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='grey'

  # Show branch name without truncation
  typeset -g POWERLEVEL9K_VCS_SHORTEN_LENGTH=
  typeset -g POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=

  # Don't show git status for repositories in these directories
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'

  # =============================================================================
  # Node Version Settings
  # =============================================================================

  # Show Node version only in directories with Node-related files
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  # Node colors
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND='green'
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND='white'

  # =============================================================================
  # Command Execution Time
  # =============================================================================

  # Show command execution time if it exceeds this threshold (seconds)
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3

  # Show milliseconds for commands that took less than this
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2

  # Colors
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='yellow'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

  # =============================================================================
  # Status (Exit Code)
  # =============================================================================

  # Don't show status for successful commands
  typeset -g POWERLEVEL9K_STATUS_OK=false

  # Show status for failed commands
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='white'

  # =============================================================================
  # Background Jobs
  # =============================================================================

  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='purple'
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='white'

  # =============================================================================
  # Time
  # =============================================================================

  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
  typeset -g POWERLEVEL9K_TIME_BACKGROUND='white'
  typeset -g POWERLEVEL9K_TIME_FOREGROUND='black'

  # =============================================================================
  # Context (User@Host)
  # =============================================================================

  # Only show context for root user or SSH sessions
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='white'
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='red'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND='white'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND='yellow'

  # Don't show context for the default user
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  # =============================================================================
  # OS Icon
  # =============================================================================

  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='white'
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='black'

  # =============================================================================
  # Transient Prompt
  # =============================================================================

  # Trim previous prompts to a simpler form after command execution
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  # =============================================================================
  # Hot Reload
  # =============================================================================

  # Enable hot reload of configuration
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file to overwrite
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
